function InitException(message, error) {
  this.message = message
  this.name = 'InitException'
  this.error = error
}
export { InitException }
